In [1]:
import yfinance as yf
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [2]:
df = yf.download("META", start="2010-01-01", end="2023-01-01", actions=True)

[*********************100%***********************]  1 of 1 completed


In [3]:
df.columns = [col[0] for col in df.columns]

In [4]:
df.head()

Close  Dividends       High        Low       Open  \
Date                                                                
2012-05-18  38.084522        0.0  44.828761  37.855398  41.889986   
2012-05-21  33.900505        0.0  36.520498  32.874426  36.390992   
2012-05-22  30.882032        0.0  33.462177  30.822261  32.485906   
2012-05-23  31.878227        0.0  32.376325  31.240663  31.250625   
2012-05-24  32.904305        0.0  33.083620  31.649101  32.824611   

            Stock Splits     Volume  
Date                                 
2012-05-18           0.0  573576400  
2012-05-21           0.0  168192700  
2012-05-22           0.0  101786600  
2012-05-23           0.0   73600000  
2012-05-24           0.0   50237200

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2673 entries, 2012-05-18 to 2022-12-30
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Close         2673 non-null   float64
 1   Dividends     2673 non-null   float64
 2   High          2673 non-null   float64
 3   Low           2673 non-null   float64
 4   Open          2673 non-null   float64
 5   Stock Splits  2673 non-null   float64
 6   Volume        2673 non-null   int64  
dtypes: float64(6), int64(1)
memory usage: 167.1 KB


In [6]:
df=df[['Close']]

In [7]:
forecast=30

In [8]:
df['Prediction']=df[['Close']].shift(-forecast)

In [9]:
df.head()

Close  Prediction
Date                             
2012-05-18  38.084522   30.652910
2012-05-21  33.900505   31.081272
2012-05-22  30.882032   31.350245
2012-05-23  31.878227   31.609255
2012-05-24  32.904305   32.047577

In [10]:
df.tail()

Close  Prediction
Date                              
2022-12-23  117.590805         NaN
2022-12-27  116.435219         NaN
2022-12-28  115.180023         NaN
2022-12-29  119.802368         NaN
2022-12-30  119.882057         NaN

In [11]:
X=np.array(df.drop(['Prediction'],1))
X=X[:-forecast]
print(X)

[[ 38.08452225]
 [ 33.90050507]
 [ 30.88203239]
 ...
 [113.78534698]
 [116.63447571]
 [112.79911804]]


C:\Users\KAANANE Youssef\AppData\Local\Temp\ipykernel_8556\1710317670.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X=np.array(df.drop(['Prediction'],1))


In [12]:
y=np.array(df['Prediction'])
y=y[:-forecast]
print(y)

[ 30.65291023  31.08127213  31.35024452 ... 115.18002319 119.80236816
 119.88205719]


In [13]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [14]:
svr_rbf=SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(x_train,y_train)

SVR(C=1000.0, gamma=0.1)

In [15]:
svm=svr_rbf.score(x_test,y_test)
svm

0.9357873481193922

In [16]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [17]:
lr_score=lr.score(x_test,y_test)
lr_score

0.9383810371460591

In [18]:
x_forecast=np.array(df.drop(['Prediction'],1))[-forecast:]

C:\Users\KAANANE Youssef\AppData\Local\Temp\ipykernel_8556\3615907597.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x_forecast=np.array(df.drop(['Prediction'],1))[-forecast:]


In [19]:
print(x_forecast)

[[111.02587891]
 [111.62361145]
 [109.44194031]
 [111.01593018]
 [111.81288147]
 [110.98605347]
 [108.36605072]
 [109.04345703]
 [117.65058136]
 [119.98168945]
 [123.02007294]
 [121.9641037 ]
 [113.68572235]
 [113.4964447 ]
 [114.89111328]
 [115.45895386]
 [114.27348328]
 [119.69278717]
 [121.12729645]
 [115.70800781]
 [118.9755249 ]
 [114.0443573 ]
 [116.64442444]
 [119.30426025]
 [116.67430878]
 [117.59080505]
 [116.43521881]
 [115.18002319]
 [119.80236816]
 [119.88205719]]


In [22]:
lr_pred=lr.predict(x_forecast)
lr_pred


array([113.39464284, 113.97140184, 111.86628227, 113.38504319,
       114.15403066, 113.35621481, 110.82814403, 111.48178117,
       119.78689442, 122.03620743, 124.96797859, 123.94906173,
       115.96115637, 115.77852019, 117.12425194, 117.67216784,
       116.52829364, 121.75744229, 123.14161679, 117.91248286,
       121.06534768, 116.30720735, 118.81604203, 121.3825482 ,
       118.84487778, 119.72921557, 118.61417712, 117.40302443,
       121.86317825, 121.94007111])

In [23]:
svm_pred=svr_rbf.predict(x_forecast)
svm_pred

array([117.74070415, 117.39466209, 114.96635173, 117.74465185,
       117.34896402, 117.75546969, 111.43058946, 113.57915194,
       120.58341042, 123.99713886, 128.20671012, 127.71382087,
       121.48981305, 120.93548375, 123.33841356, 123.46087975,
       122.7626912 , 122.90885205, 126.94603087, 123.44214779,
       120.50320286, 122.35734175, 122.71917348, 121.48259195,
       122.67210654, 120.71285406, 123.00269629, 123.43172453,
       123.32658002, 123.62764479])